name: Test Pipeline
on:
  workflow_dispatch: # This allows you to manually click "Run workflow" later
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Notify ClockingPulse (Start)
        uses: ./
        with:
          token: ${{ secrets.CLOCKING_PULSE_TOKEN }}
          state: 'run'
          api_url: 'https://www.clockingpulse.com'
          
      - name: Run Dummy Test
        run: |
          echo "Testing ClockingPulse Pipeline Webhook!"
          sleep 5
          echo "Test passed."
          
      - name: Notify ClockingPulse (Complete)
        if: success()
        uses: ./
        with:
          token: ${{ secrets.CLOCKING_PULSE_TOKEN }}
          state: 'complete'
          api_url: 'https://www.clockingpulse.com'

      - name: Notify ClockingPulse (Fail)
        if: failure()
        uses: ./
        with:
          token: ${{ secrets.CLOCKING_PULSE_TOKEN }}
          state: 'fail'
          api_url: 'https://www.clockingpulse.com'
